name: Backend CI/CD to EC2

on:
  push:
    branches:
      - main
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (CI validation)
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install backend dependencies (CI)
        run: |
          cd backend
          npm install

      - name: Deploy Backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            set -e

            cd /home/ec2-user/First_AWS_Project
            git pull origin main

            cd backend
            npm install --only=prod

            pm2 reload backend-app || pm2 start server.js --name backend-app
