name: Deploy Frontend to S3

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write   
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::217190816707:role/github-frontend-role
          aws-region: ap-south-1

      - name: Install dependencies
        working-directory: frontend
        run: npm install

      - name: Build frontend
        working-directory: frontend
        run: npm run build

      - name: Deploy to S3
        run: |
          aws s3 sync frontend/build s3://taskfrontend.shop --delete
